### ISSUE TITLE
Failed to start build runner 'jirareporter'

### ISSUE THREAD

**Issue by dudarkoas** [mamirov/jirareporter#1]
Step 2/2: JiraReportertest (JIRA Reporter)

[11:02:53][Step 2/2] 

ISSUE: TEST-001

Title: Вхождение в работу

Description: Вхождение в работу

[11:02:54][Step 2/2] Failed to start build runner 'jirareporter'

[11:02:54][Step 2/2] java.lang.NullPointerException

```
at com.amirov.jirareporter.teamcity.TeamCityXMLParser.parseXML(TeamCityXMLParser.java:42)

at com.amirov.jirareporter.teamcity.TeamCityXMLParser.getBuildData(TeamCityXMLParser.java:51)

at com.amirov.jirareporter.teamcity.TeamCityXMLParser.getBuildAttribute(TeamCityXMLParser.java:55)

at com.amirov.jirareporter.teamcity.TeamCityXMLParser.getStatusBuild(TeamCityXMLParser.java:80)

at com.amirov.jirareporter.teamcity.TeamCityXMLParser.getTestResultText(TeamCityXMLParser.java:125)

at com.amirov.jirareporter.Reporter.report(Reporter.java:20)

at com.amirov.jirareporter.JIRABuildProcess.start(JIRABuildProcess.java:49)

at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:58)

at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)

at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)

at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)

at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)

at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)

at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)

at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)

at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)

at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)

at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)

at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)

at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)

at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)

at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)

at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)

at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)

at jetbrains.buildServer.agent.impl.BuildRunAction.doStages(BuildRunAction.java:70)

at jetbrains.buildServer.agent.impl.BuildRunAction.runBuild(BuildRunAction.java:50)

at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:248)

at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:48)

at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:221)

at java.lang.Thread.run(Unknown Source)
```

[11:02:54][Step 2/2] Step JiraReportertest (JIRA Reporter) failed with unexpected error

**Comment by mamirov** [comment]
Какая версия TeamCity?
Попробуйте еще проверить данные для авторизации TeamCity

**Comment by dudarkoas** [comment]
![image](https://f.cloud.github.com/assets/6175447/1740230/7c866f3a-63bf-11e3-9440-99c0bb796e87.png)
Professional 8.0.5 (build 27692)
Данные авторизации для Jira и TeamCity заданы верно (перепроверил дважды).

**Comment by mamirov** [comment]
Боюсь что баг в неправильном указании адреса сервера тимсити и джиры
Вид адреса должен быть таким:
http://teamcity.ru

Без слэша на конце, возможно таким образом он получается неправильный путь

**Comment by dudarkoas** [comment]
Грохнул слэши, указал адрес в виде http://computername.domain.ru
ошибка та же

**Comment by mamirov** [comment]
Попробуйте открыть в браузере выгруженную xml.
Как это сделать:
- Запустите ваш билд
- Введите в адресную строку урл типа : адрес тимсити сервера + /httpAuth/app/rest/builds?locator=branch:default:any,running:true,buildType: + название вашей билд конфигурации
  И посмотрите, выгружается ли xml

В вашем случае, ссылка выглядит таким образом:
http://localhost/httpAuth/app/rest/builds?locator=branch:default:any,running:true,buildType:testjiraplugin

**Comment by mamirov** [comment]
Если не помогло, в таком случае:
- Зайдите в папку билдагента
- Далее папка bin
- Открыть файл params.properties
- Сообщите параметр "build.xml.url"

**Comment by dudarkoas** [comment]
![image](https://f.cloud.github.com/assets/6175447/1740491/93a746f8-63c9-11e3-96db-18be0ffea4c1.png)
Случайно ткнул на закрыть-открыть. 
В билдагенте адрес для xml-ки имеется.
xml во время запуска на скрине выше

**Comment by mamirov** [comment]
В таком случае сообщите данные из моего предыдущего комментария, из файла params.properties

**Comment by mamirov** [comment]
Сообщите мне адрес для xml-ки

**Comment by dudarkoas** [comment]
build.xml.url=http://COMP.DOMAIN.ru/httpAuth/app/rest/builds?locator\=branch:default:any,running:true,buildType:null

**Comment by mamirov** [comment]
Ошибка ясна, buildType равен null
Посмотрите еще параметр teamcity.buildType.id
Если такого параметра нет, а есть просто параметр buildType, то это действительно баг

**Comment by dudarkoas** [comment]
сочетания символов buildType.id в файле params.properties нет

**Comment by mamirov** [comment]
перезалил плагин, попробуйте скачать по новой, была старая версия плагина

**Comment by mamirov** [comment]
https://bitbucket.org/mamirov/jirareporter/downloads/jirareporter.zip

**Comment by dudarkoas** [comment]
остановил сервер и билд агент
удалил плагин из  .BuildServer\plugins\
папку плагина из .BuildServer\plugins.unpacked\
удалил папку плагина из BuildAgent\plugins\
закинул новый архив в папку .BuildServer\plugins\
запустил сервак и агента
агент обновился
запустил задачу
та же ошибка, так же buildType:null

**Comment by mamirov** [comment]
Обновил плагин, попробуйте еще раз

**Comment by dudarkoas** [comment]
Аналогичный путь пройден - аналогичная ошибка.

**Comment by mamirov** [comment]
Сейчас перепроверил новую сборку плагина, обновил его, должно работать, попробуйте еще раз

**Comment by mamirov** [comment]
Также посмотрите параметр "teamcity.buildType.id" в файле params.properties, он должен присутствовать, данный файл перезаписывается после запуска билда

**Comment by dudarkoas** [comment]
Нету такого параметра в этом файле... Запуск заканчивается той же ошибкой.

**Comment by mamirov** [comment]
Вы бы могли в таком случае скинуть всю информацию из файла params.properties? Предварительно убрав данные авторизации
Еще скажите версию плагина в пункте TeamCity - "Plugin List"

**Comment by mamirov** [comment]
Скорее ошибка заключается в новой версии TeamCity, выгрузка данного параметра осуществляется другим образом

Добавлено. Так и есть, с версии 8.0.4, плагин будет пофиксен ожидайте

**Comment by mamirov** [comment]
https://bitbucket.org/mamirov/jirareporter/downloads/jirareporter.zip

Исправлено, новая версия плагина

**Comment by dudarkoas** [comment]
Проверено - работает.
Было бы круто работать с несколькими Issue одновременно.

**Comment by mamirov** [comment]
Вы можете также указывать id задач через запятую
Например:
EXAMPLE-1,EXAMPLE-2 и так далее

Спасибо что напомнили это указать в вики :)

**Comment by dudarkoas** [comment]
А шаблон комментария можно редактировать? Пока коммент выглядит следующим образом:
[ SUCCESS Build Finished Results: [testjiraplugin : Step 2/2|http://COMP.DOMAIN.ru/viewLog.html?buildId=468&tab=buildResultsDiv&buildTypeId=bt7] ]

**Comment by mamirov** [comment]
Шаблон к сожалению нет, но думаю можно прикрутить такую фичу, если хотите можете оформить тикет здесь, оставив пожелания на новый функционал, либо если у вас есть ява программисты вы можете скачать исходники и пересобрать плагин.

**Comment by mamirov** [comment]
То есть комментарий не трансформировался в джире должным образом? А прямо отображает тэги?

**Comment by dudarkoas** [comment]
Да, эток копипаст с Jira после отработки плагина.
Ок, оформлю пожелание.
