### ISSUE TITLE
Failed builds cause failed jirareport build step

### ISSUE THREAD

**Issue by robiter** [mamirov/jirareporter#10]
Hi,

When the configuration is failing, the last build step (jirareporter) is failing as well. It does everything it suppose to do well (updates jira with status and comments), but i see that the jirareporter step is marked as failed in TC with this error log:

[Step 2/2] Failed to start build runner 'jirareporter'
java.lang.NullPointerException
    at com.amirov.jirareporter.jira.JIRAClient.getTransitionInput(JIRAClient.java:56)
    at com.amirov.jirareporter.Reporter.progressIssue(Reporter.java:34)
    at com.amirov.jirareporter.JIRABuildProcess.start(JIRABuildProcess.java:55)
    at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:58)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.doProcessNextStep(StepExecutor.java:89)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:44)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:77)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
    at jetbrains.buildServer.agent.impl.BuildRunAction.doStages(BuildRunAction.java:70)
    at jetbrains.buildServer.agent.impl.BuildRunAction.runBuild(BuildRunAction.java:50)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:243)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:48)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:216)
    at java.lang.Thread.run(Unknown Source)
[14:32:26][Step 2/2] Step Generate Jira Reprot (JIRA Reporter) failed with unexpected error

Hope my QA is good for you :)

Thanks

**Comment by mamirov** [comment]
Hi )
This error cause when you write wrong jira workflow and Jirareporter not find this transition for status "Open"
Example, when you jira ticket have status "Open", but you write jira workflow in plugin jirareporter:
SUCCESS:In Testing-Resolve;
FAILURE:In Testing-Reopen;
In this workflow cannot find status for your ticket, but was is "In Testing"
Second Example:
SUCCESS:Open-Test;
FAILURE:Open-Rechpoken;
In this workflow plugin cannot find transition "Test", "Rechpoken" for your status

**Comment by robiter** [comment]
Thats right.
