### ISSUE TITLE
Templates for messsages.

### ISSUE THREAD

**Issue by dudarkoas** [mamirov/jirareporter#2]
Would be best if i could make changes in templates of messages.

**Comment by mamirov** [comment]
Download updated plugin from here and test:
https://bitbucket.org/mamirov/jirareporter/issue-attachment/1/mamirov/jirareporter/1387191892.16/1/jirareporter.zip

How to use:
- Enable checkbox for editing template comment of JIRA;
- Also you have defined parameters:

```
*status.build*, *build.type.name*, *tests.results*, *teamcity.server.url*, *build.id*, *build.type*.
```

Example comment template:

```
*build.type.name* : *status.build* 
*test.results* 
Template example.
```

**Comment by dudarkoas** [comment]
Не могу запустить на агенте:
Incompatible runner: JIRA Reporter
Можешь скомпилировать на предыдущей версии Java? Я полагаю проблема в том, что там 6ая версия Java. Проапдейтиить ее немогу, т.к. там помимо моего билдагента еще пачка сервисов, которые админю не я и они могут поотваливаться
В свою очередь на локальном компе у меня запускается отлично, спасибо.

**Comment by mamirov** [comment]
https://bitbucket.org/mamirov/jirareporter/issue-attachment/1/mamirov/jirareporter/1387252907.15/1/jirareporter.zip

Попробуй проверить, поменял на 6ую версию Java

Еще понятно ли по переменным, нормально ли указывать значения?

**Comment by dudarkoas** [comment]
Статус билда: _status.build_
Имя билда: _build.type.name_
Результаты теста(если есть): _tests.results_
Адрес: _teamcity.server.url_/viewLog.html?buildId=_build.id_&tab=buildResultsDiv&buildTypeId=_build.type_
Тикеты: %ISSUES%
Вот так использую пока что.
Сейчас попробую на серваке, спасибо.

**Comment by mamirov** [comment]
Incompatible runner: JIRA Reporter

Кстати ошибка скорее всего не на стороне сервера может быть, а на стороне агента где будет запускаться билд.

**Comment by dudarkoas** [comment]
Так и есть, на сервере ругается на билдраннер агента:
Incompatible runner: JIRA Reporter
Пока не разрешил, с новым файлом то же самое.

**Comment by mamirov** [comment]
Попробуй зайти в раздел своей билд конфигурации "Agents Requirements", там обычно пишется причина не запуска

Либо соответственно посмотреть лог файл у билд агента buildagent directory/logs/

**Comment by dudarkoas** [comment]
ERROR - gins.spring.SpringPluginLoader - Failed to initialize spring context for plugin jirareporter 
org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.amirov.jirareporter.JIRARunner] for bean with name 'jiraRunner' defined in plugin: jirareporter#jirareporter-agent.jar!/META-INF/build-agent-plugin-jirareporter.xml: problem with class file or dependent class; nested exception is java.lang.UnsupportedClassVersionError: com/amirov/jirareporter/JIRARunner : Unsupported major.minor version 51.0
    at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1253)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:576)
    at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1319)
    at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:885)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:562)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
    at jetbrains.buildServer.plugins.spring.SpringPluginLoader.pluginClassesLoaded(SpringPluginLoader.java:72)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:115)
    at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:67)
    at $Proxy7.pluginClassesLoaded(Unknown Source)
    at jetbrains.buildServer.plugins.PluginManagerImpl$2.visitPlugin(PluginManagerImpl.java:122)
    at jetbrains.buildServer.plugins.PluginsCollection.foreachLoadedPlugins(PluginsCollection.java:107)
    at jetbrains.buildServer.plugins.PluginManagerImpl.firePluginClassesLoaded(PluginManagerImpl.java:120)
    at jetbrains.buildServer.plugins.PluginManagerImpl.loadPlugins(PluginManagerImpl.java:80)
    at jetbrains.buildServer.agent.plugins.AgentPluginsLoader.initializePlugins(AgentPluginsLoader.java:63)
    at jetbrains.buildServer.agent.AgentMain2.loadPlugins(AgentMain2.java:140)
    at jetbrains.buildServer.agent.AgentMain2.main(AgentMain2.java:41)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at jetbrains.buildServer.agent.AgentMain.main(AgentMain.java:41)
Caused by: java.lang.UnsupportedClassVersionError: com/amirov/jirareporter/JIRARunner : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$000(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.doLoadClass(TeamCityClassLoader.java:68)
    at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.loadClass(TeamCityClassLoader.java:37)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at org.springframework.util.ClassUtils.forName(ClassUtils.java:257)
    at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:408)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1271)
    at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1242)
    ... 25 more

**Comment by mamirov** [comment]
Да, проблема в версии явы, видимо у меня не скомилировалось предыдущей версией

Попробую еще раз

**Comment by mamirov** [comment]
https://bitbucket.org/mamirov/jirareporter/issue-attachment/1/mamirov/jirareporter/1387260513.96/1/jirareporter.zip

Обновил

**Comment by dudarkoas** [comment]
Работает, спасибо!
