### ISSUE TITLE
exception startng jirareporter 0.1

### ISSUE THREAD

**Issue by gcody** [mamirov/jirareporter#4]
I am using teamcity-8.0.5 and installed jira-reporter-0.1 plugin.  I have jira-4.3.4.
I added buildstep with jirareporter as last step.
The ticket in jira does exist. The teamcity user has permission to update it.
The ticket is of type 'Other'. The ticket is Open.
Enable Issue Processing is checked.
Enablee SSL is not checked.

SUCCESS:In Open-Close Issue,In Testing-Close Issue,Open-Close Issue;
FAILURE:Closed-Open Issue,In Resolved-Open Issue, In Testing-Open Issue;
My atlassian-security-log shows teamcity user connecting successfully.

I see this in agent log:
Description: Used to track the success/failure of the build. Teamcity will update
[11:07:47][Step 5/5] Failed to start build runner 'jirareporter'
[11:07:47][Step 5/5] com.atlassian.jira.rest.client.RestClientException: at com.atlassian.jira.rest.client.internal.jersey.AbstractJerseyRestClient.invoke(AbstractJerseyRestClient.java:68) at com.atlassian.jira.rest.client.internal.jersey.AbstractJerseyRestClient.post(AbstractJerseyRestClient.java:135) at com.atlassian.jira.rest.client.internal.jersey.JerseyIssueRestClient.addComment(JerseyIssueRestClient.java:367) at com.amirov.jirareporter.Reporter.report(Reporter.java:22) at com.amirov.jirareporter.JIRABuildProcess.start(JIRABuildProcess.java:50) at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:58) at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25) at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18) at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78) at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37) at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18) at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43) at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25) at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138) at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123) at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83) at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44) at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31) at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24) at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78) at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37) at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24) at jetbrains.buildServer.agent.impl.BuildRunAction.doStages(BuildRunAction.java:70) at jetbrains.buildServer.agent.impl.BuildRunAction.runBuild(BuildRunAction.java:50) at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:248) at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:48) at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:221) at java.lang.Thread.run(Unknown Source) Caused by: com.sun.jersey.api.client.UniformInterfaceException: Client response status: 404 at com.sun.jersey.api.client.WebResource.voidHandle(WebResource.java:628) at com.sun.jersey.api.client.WebResource.post(WebResource.java:223) at com.atlassian.jira.rest.client.internal.jersey.AbstractJerseyRestClient$6.call(AbstractJerseyRestClient.java:141) at com.atlassian.jira.rest.client.internal.jersey.AbstractJerseyRestClient$6.call(AbstractJerseyRestClient.java:135) at com.atlassian.jira.rest.client.internal.jersey.AbstractJerseyRestClient.invoke(AbstractJerseyRestClient.java:54) ... 27 more
[11:07:47][Step 5/5] Step report (JIRA Reporter) failed with unexpected error

**Comment by mamirov** [comment]
Are you downloading latest plugin from here?
https://bitbucket.org/mamirov/jirareporter/downloads/jirareporter.zip

Plugin updated 17.12.2013

**Comment by mamirov** [comment]
if you downloading older plugin with name jirareporter-0.1.zip, this maybe work wrong

**Comment by gcody** [comment]
Hello I downloaded from the link you provided. I stopped both teamcity server and agent. I removed plugin from server unpacked folder and agent plugin folder. Then installed latest 0.1 and started both. I still see exactly same error.

The jirareporter is retrieving the ticket subject and description from our jira which it prints to the log immediately before crashing. 
ISSUE: XYZ-1234 
Title: TeamCity Build trunk Status 
Description: Used to track the success/failure of the build. Teamcity will update

Is the 404 error in the log from the teamcity login? I double-checked all the config items for the teamcity config within the jirareporter. It has the correct name/password/url  (url is our base teamcitiy login page)

**Comment by gcody** [comment]
closed ticket by accident

**Comment by mamirov** [comment]
404 error, not found page. Maybe he cannot find correct url for work with jira api, because you use older jira version, i see this tommorow, thanks for reporting.

**Comment by gcody** [comment]
Let me know if I can provide more info or if you have another change you would like me to try
(FYI Unfortunately i cannot upgrade to a newer jira version at this time).

**Comment by mamirov** [comment]
Can you run jirareporter without issue progressing?

Send me your build agent log and error message from build log TeamCity.

When you run jirareporter you jira issue have status "In Testing"?

**Comment by mamirov** [comment]
You status of JIRA issue named 'Open' or 'In Open' ?

**Comment by gcody** [comment]
Hello To answer your questions
I turned off issue progressing and saw the same error. What is the plugin supposed to do differently?
I used the values from your example on the wiki page.
 I also tried with just SUCCESS:Open-Close; FAILURE:Close-Open;

**Comment by mamirov** [comment]
I see this problem on holidays, because i can't install jira-4.3.4 on MAC OS
