### ISSUE TITLE
Failed to start build runner 'jirareporter'

### ISSUE THREAD

**Issue by robiter** [mamirov/jirareporter#8]
Hi mamirov,
I have yet another issue.
## When running the build step this is what i get from TC build log:

Step 2/2: Jira report (JIRA Reporter) (1s)
[11:35:13]
[Step 2/2] Failed to start build runner 'jirareporter'
java.lang.NullPointerException
    at com.amirov.jirareporter.teamcity.TeamCityXMLParser.parseXML(TeamCityXMLParser.java:51)
    at com.amirov.jirareporter.teamcity.TeamCityXMLParser.<init>(TeamCityXMLParser.java:26)
    at com.amirov.jirareporter.Reporter.<init>(Reporter.java:14)
    at com.amirov.jirareporter.JIRABuildProcess.start(JIRABuildProcess.java:31)
    at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:58)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.doProcessNextStep(StepExecutor.java:89)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:44)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:77)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
    at jetbrains.buildServer.agent.impl.BuildRunAction.doStages(BuildRunAction.java:70)
    at jetbrains.buildServer.agent.impl.BuildRunAction.runBuild(BuildRunAction.java:50)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:243)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:48)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:216)
    at java.lang.Thread.run(Unknown Source)
[11:35:13][Step 2/2] Step Jira report (JIRA Reporter) failed with unexpected error

---

I us the latest version you sent me today (19/12/13).
This happens when using 'Enable issue progressing' and also when not using it.

Thanks.

**Comment by mamirov** [comment]
This maybe not work on TeamCity 7.1. version, because TeamCity Rest API have older version and not supported some parameters, i see this problem, thanks for reporting.

Send me parameters "build.xml.url" and "build.type.id" from buildagent directory/bin/params.properties

**Comment by mamirov** [comment]
This bug must be fix in new version plugin

You write wrong format your URLs for TeamCity, correct URL is should be "http://teamcity.mycompany.com", without last slash

**Comment by mamirov** [comment]
Also you download fixed plugin from here:
https://bitbucket.org/mamirov/jirareporter/issue-attachment/1/mamirov/jirareporter/1387450491.72/1/jirareporter.zip

**Comment by robiter** [comment]
Boom! The fix is working, I get comments and workflow on JIRA.

Thanks dude, great plugin!

**Comment by mamirov** [comment]
Thank you for reporting :)
If you have any question you are welcome :)

**Comment by polive96** [comment]
that link is no longer working to download. got a new one?
